name: poc_street_path
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.8

  intl: ^0.20.2 # To manage string data.
  flutter_riverpod: ^3.0.1 # To manage state and DI.
  dio: ^5.9.0 # To make http request.
  flutter_dotenv: ^6.0.0 # Env manager.

  flutter_p2p_connection: ^3.0.3 # Communication for Street Path

dev_dependencies:
  flutter_test:
      sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/images/
    - .env